# chunks will have a set size of 12 x 12
CHUNK_WIDTH = CHUNK_HEIGHT = 12
CHUNK_TILE_WIDTH = CHUNK_TILE_HEIGHT = 64
CHUNK_WIDTH_PIX = CHUNK_WIDTH * CHUNK_TILE_WIDTH
CHUNK_HEIGHT_PIX = CHUNK_HEIGHT * CHUNK_TILE_HEIGHT
CHUNK_TILE_AREA = (CHUNK_TILE_WIDTH, CHUNK_TILE_HEIGHT)

TILE_X = 0
TILE_Y = 1
TILE_IMG = 2
TILE_COL = 3



# serialization
CHUNK_TILEMAP_KEY = "tile"
CHUNK_POS_KEY = "pos"
CHUNK_IMAGES_KEY = "images"

ANIMATION_PATH_KEY = "a_path"
ANIMATION_NAME_KEY = "a_name"

ENTITY_RECT_KEY = "rect"
ENTITY_ANIMATION_KEY = "animation"
ENTITY_TYPE_KEY = "type"

HANDLER_DATA_KEY = "entities"
HANDLER_ANIMATION_KEY = "animation"

WORLD_DATA_KEY = "world"
WORLD_CHUNK_KEY = "chunks"

STATE_HANDLER_KEY = "handler"
STATE_WORLD_KEY = "world"



# world rendering

SPRITE_OBJECT_PREFIX = "spr_o_"

SPRITE_OBJECT_KEY = "sprite"
