# chunks will have a set size of 12 x 12
CHUNK_WIDTH = CHUNK_HEIGHT = 12
CHUNK_TILE_WIDTH = CHUNK_TILE_HEIGHT = 64
CHUNK_WIDTH_PIX = CHUNK_WIDTH * CHUNK_TILE_WIDTH
CHUNK_HEIGHT_PIX = CHUNK_HEIGHT * CHUNK_TILE_HEIGHT
CHUNK_TILE_AREA = (CHUNK_TILE_WIDTH, CHUNK_TILE_HEIGHT)

TILE_X = 0
TILE_Y = 1
TILE_IMG = 2
TILE_COL = 3



# serialization
CHUNK_TILEMAP_KEY = "tile"
CHUNK_POS_KEY = "pos"
CHUNK_IMAGES_KEY = "images"
